### ISSUE TITLE
Times behave strangely

### ISSUE THREAD

**Issue by sporto** [lukewestby/ellie#15]
In my repl I do this

```
> time = 1506816000000
1506816000000 : number

> date = Date.fromTime time
<Sun Oct 01 2017 00:00:00 GMT+0000 (UTC)> : Date.Date
```

So `1506816000000` is Oct 01 2017. Double checked with https://www.epochconverter.com/

Then in Ellie I have this code:

```
-- GMT: Sunday, 1 October 2017 00:00:00
time = 
    1506816000000
    
date = 
    Date.fromTime time
    
main : Html msg
main =
    text (toString date)
```

https://ellie-app.com/SvzsPftca1/2

Output window shows: 

`<Wed Dec 24 1969 03:41:19 GMT+1100 (AEDT)>`

![image](https://user-images.githubusercontent.com/1005498/31922179-4d6b3128-b8bf-11e7-8581-ad8c16272806.png)

**Comment by lukewestby** [comment]
hey @sporto, thanks for reporting. this is a problem with the handling of int literals by the compiler, which i think ghcjs exaggerates to be a bit worse than on native platforms. the code for the value `time` is being generated incorrectly:

<img width="300" alt="screen shot 2017-10-24 at 8 59 41 am" src="https://user-images.githubusercontent.com/1508245/31954174-b6cc5262-b899-11e7-87f1-902a52c05396.png">

more info on the problem at https://github.com/elm-lang/elm-compiler/issues/1246

since i can't fix this directly i'm gonna close the issue and track it in a meta issue
