### ISSUE TITLE
Saving doesn't work

### ISSUE THREAD

**Issue by joneshf** [lukewestby/ellie#26]
# SSCCE

1. Go to https://ellie-app.com/new
1. Click "SAVE"
1. Button changes to "SAVING..."
1. Nothing else happens

# Screenshot
![screenshot-1513896725](https://user-images.githubusercontent.com/1356417/34278442-ab498600-e65f-11e7-9cd6-a2f7ed9ac91e.png)

It appears to be from a recent change to https://github.com/lukewestby/ellie/blob/148adf22594aca6891b3c630de53315116fbb133/client/src/Pages/Editor/index.js#L108-L119

Looks like the change to be a block should also be accompanied by an explicit return of the promise. Or, change back to not being a block. Either one should fix this issue. Or, something entirely different!

Let me know if you'd like a PR or if you have an alternative fix in mind.

**Comment by lukewestby** [comment]
@joneshf I pushed up a fix for this one as soon as I saw the issue so that folks can start saving again. All I did was add a return like you said (tfw you're too used to implicit returns) but I think the ideal thing would be to have the purescript app return an array of strings on `Success` instead of a blob so that we don't need to read the file at all. I would love a PR that does that!

**Comment by lukewestby** [comment]
As a side note and a matter of design, I really dislike the way that save and run are distinguished right now with that local boolean state. I rushed it so I could ship the browser compiler stuff and here it is coming back to bite.
